version: "3.3"

services:
  database:
    image: postgres:15
    container_name: postgres_symfony_database
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgres/data
    networks:
      - postgresnetwork
    env_file:
      - .env.dev

volumes:
  database:

networks:
  postgresnetwork:
    driver: bridge